# gmake
# This file is automatically generated for client.mk.
# Do not edit. Edit /tmp/mozilla/.mozconfig instead.
# To create a new .mozconfig file, you can visit,
#   http://webtools.mozilla.org/build/config.cgi

# PATH=/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games:/opt/jakarta-ant-1.5.1/bin
MOZ_THUNDERBIRD=1
