# gmake
# This file is automatically generated for client.mk.
# Do not edit. Edit /cygdrive/c/build/trees/src/mozilla/.mozconfig instead.
# To create a new .mozconfig file, you can visit,
#   http://webtools.mozilla.org/build/config.cgi

# PATH=/cygdrive/c/WINDOWS/system32:/cygdrive/c/WINDOWS:/cygdrive/c/WINDOWS/System32/Wbem:/cygdrive/c/Program Files/Microsoft Visual Studio/Common/Tools/WinNT:/cygdrive/c/Program Files/Microsoft Visual Studio/Common/MSDev98/Bin:/cygdrive/c/Program Files/Microsoft Visual Studio/Common/Tools:/cygdrive/c/Program Files/Microsoft Visual Studio/VC98/bin:/cygdrive/c/build/tools/moztools/bin:/usr/bin
# --enable-crypto is used by configure (not client.mk)
# --disable-mathml is used by configure (not client.mk)
# --disable-installer is used by configure (not client.mk)
# --disable-activex is used by configure (not client.mk)
# --disable-activex-scripting is used by configure (not client.mk)
# --disable-tests is used by configure (not client.mk)
# --disable-oji is used by configure (not client.mk)
# --disable-necko-disk-cache is used by configure (not client.mk)
# --disable-debug is used by configure (not client.mk)
# --enable-optimize is used by configure (not client.mk)
# --disable-profilesharing is used by configure (not client.mk)
# --enable-extensions=wallet,spellcheck is used by configure (not client.mk)
# --enable-necko-protocols=http,file,jar,viewsource,res,data is used by configure (not client.mk)
# --enable-image-decoders=icon,png,gif,jpeg is used by configure (not client.mk)
MOZ_THUNDERBIRD=1
